var data = [
    'Contractor: : Nhà thầu',
    'Owner: : Chủ nhà, Chủ đầu tư',
    'Resident architect: : Kiến trúc sư thường trú',
    'Supervisor: : giám sát',
    'Site engineer: : Kỹ sư công trường',
    'Structural engineer: : Kỹ sư kết cấu',
    'Construction engineer: :  Kỹ sư xây dựng',
    'Electrical engineer: : Kỹ sư điện',
    'Water works engineer: : Kỹ sư xử lý nước',
    'Mechanical engineer: : Kỹ sư cơ khí',
    'Soil engineer: : Kỹ sư địa chất',
    'Mate: : Thợ phụ',
    'Mason: : Thợ hồ',
    'Bricklayer: : Thợ hồ',
    'Plasterer: : Thợ trát',
    'Carpenter: : Thợ mộc sàn nhà , coffa',
    'Plumber: : Thợ ống nước',
    'Welder: : Thợ hàn',
    'Building site: : công trường xây dựng',
    'Brick wall: : tường gạch',
    'Carcass: : khung sườn',
    'Concrete: : bê tông',
    'Chimney: : ống khói (lò sưởi)',
    'Plank platform: : sàn lát ván',
    'Floor: : tầng',
    'First floor: : lầu một',
    'Ground floor: : tầng trệt',
    'Upper floor: : tầng trên',
    'Dining room: : Phòng ăn',
    'Wall: : Tường nhà',
    'Porch: : Mái hiên',
    'Shutter: : Cửa chớp',
    'Window: : Cửa sổ',
    'Penthouse: : căn hộ áp mái',
    'Kitchen: : Nhà bếp',
    'Yard: : Sân vườn',
    'Apartment: : Chung cư',
    'Bathroom: : Phòng tắm',
    'Bedroom: : Phòng ngủ',
    'Living room: : Phòng khách',
    'Balcony: : Ban công',
    'Downstairs: : Tầng dưới, tầng trệt',
    'Condominium: : Chung cư cao cấp',
    'Ceiling: : Trần nhà',
    'Semi-detached house: : Nhà ghép đôi, chung tường với nhà khác',
    'Detached house: : Nhà riêng lẻ, không chung tường',
    'Terraced house: : Nhà trong 1 dãy thường có kiến trúc giống nhau',
    'Cottage: : Nhà ở nông thôn',
    'Bungalow: : Nhà 1 trệt, không lầu, thường bằng gỗ',
    'Residence: : Nhà ở, dinh thự',
    'Hallway: : Hành lang',
    'Attic: : Gác xép',
    'Stair: : Cầu thang',
    'Level: : ống thăng bằng',
    'Pickaxe: : búa có đầu nhọn',
    'Nail: : cái đinh',
    'Nut: : con ốc',
    'Bolt: : bu lông',
    'Pincers: : cái kìm',
    'Saw: : cái cưa',
    'Screwdriver: : tua vít',
    'Vice: : mỏ cặp',
    'Chisel: : các đục',
    'Hammer: : búa',
    'Shear: : kéo lớn',
    'Beam: : dầm, xà',
    'Crane: : cần cẩu',
    'Crane beam: : dầm cần trục',
    'Crane girder: : giá cần trục; giàn cần trục',
    'Automatic fire door: : Cửa tự động phòng cháy',
    'Deck bridge: : Cầu có đường xe chạy trên',
    'Deck girder: : giàn cầu',
    'Spade: : cái xẻng',
    'Tape: : thước cuộn',
    'Piler: : cái kìm',
    'Wrench: : cái cờ lê',
    'Drill: : máy khoan',
    'Wheel barrow: : xe cút kít, xe đẩy tay',
    'Aerial ladder: : thang có bàn xoay',
    'Builder’s hoist: : máy nâng dùng trong xây dựng',
    'Guard board: : tấm chắn, tấm bảo vệ',
    'Concrete mixer: : máy trộn bê tông',
    'Agitator: : máy trộn',
    'Agitator Shaker: : máy khuấy',
    'AHU – Air Handling Unit: : thiết bị xử lý khí trung tâm',
    'Air barrier: : Tấm ngăn không khí',
    'Air caisson: : Giếng chìm hơi ép',
    'Air distribution system: : Hệ thống điều phối khí',
    'Air-water jet: : Vòi phun nước cao áp',
    'Alarm – Initiating device: : Thiết bị báo động ban đầu',
    'Alarm bell: : Chuông báo tự động',
    'Ammeter: : Ampe kế',
    'Anchorage: : Mấu neo',
    'Appurtenance: : Phụ tùng',
    'Diaphragm: : Dầm ngang',
    'Drainage: : Hệ thống thoát nước',
    'Anchor: : Neo',
    'Air meter: : Máy đo lượng khí',
    'Wind beam: : xà chống gió',
    'Brick: : gạch',
    'Curb: : đá',
    'Dense concrete: : bê tông nặng',
    'Density of material: : Tỷ trọng của vật liệu',
    'Corrosive agent: : Chất xâm thực',
    'Iron: : sắt',
    'Aluminum: : nhôm',
    'Argillaceous: : Sét, đất pha sét',
    'Armored concrete: : Bê tông cốt thép',
    'Dry sand: : Cát khô',
    'Cobble: : Than cục',
    'Duct: : ống chứa cốt thép dự ứng lực',
    'Dust sand: : Cát bột',
    'Commercial concrete: : bê tông trộn sẵn',
    'Automatic relay: : Công tắc điện tự động rơ le',
    'Automobile crane: : Cần cẩu đặt trên ô tô',
    'Auxiliary bridge: : Cầu phụ, cầu tạm thời',
    'Ashlar: : Đá khối',
    'Concrete aggregate: : cốt liệu bê tông (cát và sỏi)',
    'Chuting concrete: : bê tông lỏng',
    'Arenaceous: : Cốt pha',
    'Stone: : đá tảng',
    'Gravel: : sỏi',
    'Rock: : đá viên',
    'Soil: : đất',
    'Concrete: : xi măng',
    'Wood: : gỗ',
    'Steel: : thép',
    'Rubble: : đá cuội',
    'Mud: : bùn',
    'Alkali: : Kiềm',
    'Alluvial soil: : Đất phù sa bồi tích',
    'Alluvion: : Đất phù sa',
    'Stainless steel: : thép không rỉ',
    'Bag of cement: : bao xi măng',
    'Alloy steel: : thép hợp kim',
    'Plank platform: : sàn lát ván',
    'Brick wall: : tường gạch',
    'Acid-resisting concrete:',
    'Activator: : Chất hoạt hóa',
    'Active carbon: : Than hoạt tính',
    'Additive: : Chất độn, chất phụ gia thêm vào',
    'Admixture: : Phụ gia',
    'Advanced composite material:',
    'Aerated concrete: : Bê tông xốp',
    'Agent: : Chất hóa học',
    'Agglomerate-foam: : Bê tông bọt thiêu kết',
    'Aggregate: : Cốt liệu',
    'Allowable load: : tải trọng cho phép',
    'Alternate load: : tải trọng đổi dấu',
    'Anchor sliding: : độ trượt trong mối neo của đầu cốt thép',
    'Anchorage length: : chiều dài đoạn neo giữ của cốt thép',
    'Angle bar: : thép góc',
    'Angle brace: : thanh giằng góc ở giàn giáo',
    'Antisymmetrical load: : tải trọng phản đối xứng',
    'Apex load: : tải trọng ở nút (giàn)',
    'Architectural concrete: : bê tông trang trí',
    'Area of reinforcement: : diện tích cốt thép',
    'Armoured concrete: : bê tông cốt thép',
    'Arrangement of longitudinal reinforcement cut-out: : bố trí các điểm cắt đứt cốt thép dọc của dầm',
    'Arrangement of reinforcement: : bố trí cốt thép',
    'Articulated girder: : dầm ghép',
    'Asphaltic concrete: : bê tông atphan',
    'Assumed load: : tải trọng giả định, tải trọng tính toán',
    'Atmospheric corrosion resistant steel: : thép chống rỉ do khí quyển',
    'Average load: : tải trọng trung bình',
    'Axial load: : tải trọng hướng trục',
    'Axle load: : tải trọng lên trục',
    'Bag: : bao tải (để dưỡng hộ bê tông)',
    'Balance beam: : đòn cân; đòn thăng bằng',
    'Balanced load: : tải trọng đối xứng',
    'Balancing load: : tải trọng cân bằng',
    'Ballast concrete: : bê tông đá dăm',
    'Bar: : thanh cốt thép',
    'Basement of tamped concrete: : móng (tầng ngầm) làm bằng cách đổ bê tông',
    'Basic load: : tải trọng cơ bản',
    'Braced member: : thanh giằng ngang',
    'Bracing beam: : dầm tăng cứng',
    'Bracing: : giằng gió',
    'Bracket load: : tải trọng lên dầm chìa, tải trọng lên công xôn',
    'Brake beam: : đòn hãm, cần hãm',
    'Brake load: : tải trọng hãm',
    'Breaking load: : tải trọng phá hủy',
    'Breast beam: : tấm tì ngực; (đường sắt) thanh chống va',
    'Breeze concrete: : bê tông bụi than cốc',
    'Buffer beam: : thanh chống va, thanh giảm chấn (tàu hỏa)',
    'Building site latrine: : nhà vệ sinh tại công trường xây dựng',
    'Building site: : công trường xây dựng',
    'Build-up girder: : dầm ghép',
    'Built up section: : thép hình tổ hợp',
    'Bursting concrete stress: : ứng suất vỡ tung của bê tông',
    'Concrete proportioning: : Công thức pha trộn bê tông',
    'Concrete stress at tendon level: : Ứng suất bê tông ở thớ đặt cáp dự ứng lực',
    'Concrete surface treatement: : Xử lý bề mặt bê tông',
    'Concrete test hammer: : Súng bật nảy để thử cường độ bê tông',
    'Concrete thermal treatement: : Xử lý nhiệt cho bê tông',
    'Concrete unit weight, density of concrete: : Trọng lượng riêng bê tông',
    'Concrete-filled pipe pile: : Cọc ống thép nhồi bê tông lấp lòng',
    'Condition of curing: : Điều kiện dưỡng hộ bê tông',
    'Conjugate beam: : Dầm trang trí, dầm giả',
    'CONN – Connection: : Mối nối',
    'Connect by hinge: : Nối khớp',
    'Connected load: : Tải trọng liên kết',
    'Connection: : Ghép nối',
    'Connection strand by strand: : Nối các đoạn cáp dự ứng lực Kéo sau',
    'Constant along the span: : không thay đổi dọc nhịp',
    'Constant load: : tải trọng không đổi, tải trọng tĩnh',
    'Construction cost: : Giá thành thi công',
    'Construction document: : Hồ sơ thi công',
    'Construction equipment: : Thiết bị thi công',
    'Construction load: : Tải trọng thi công',
    'Construction material: : Vật liệu xây dựng',
    'Construction successive stage: : Giai đoạn thi công nối tiếp nhau',
    'Contact surface: : Bề mặt tiếp xúc',
    'Content, Dosage: : Hàm lượng',
    'Continuity factor: : Hệ số xét đến tính liên tục của các nhịp',
    'Continuous granulametry: : Cấp phối hạt liên tục',
    'Continuous load: : Tải trọng liên tục; tải trọng phân bố đều',
    'Continuous slab deck: : Kết cấu nhịp bản liên tục',
    'Continuous span: : Nhịp liên tục',
    'Contract area: : Diện tích tiếp xúc',
    'Contract: ˈkɒntrækt, əˈgriːmənt',
    'Contraction: : Co ngắn lại',
    'Contraction, shrinkage: : Co ngót',
    'Control, checking: : Kiểm tra (kiểm toán)',
    'Controlling beam: : Tia điều khiển',
    'Conventional elasticity limit: : Giới hạn đàn hồi qui ước',
    'Conventional value: : Trị số quy ước',
    'Convergent beam: : Chùm hội tụ',
    'Coordinate: : Tọa độ',
    'Copper clad steel: : Thép mạ đồng',
    'Corner connector: : Neo kiểu thép góc',
    'Corroded reinforcement: : Cốt thép đã bị rỉ',
    'Corrosion fatigue: : Mỏi rỉ',
    'Corrosive agent: : Chất xâm thực',
    'Corrosive environment agressive: : Môi trường ăn mòn',
    'Counterfort wall: : Tường chắn có các tường chống phía sau',
    'Counterpoiser, Counterbalance: : Đối trọng',
    'Coupler: : Đầu nối để nối các cốt thép dự ứng lực',
    'Cover plate: : Bản thép phủ (ở phần bản cánh dầm thép)',
    'Covered concrete section: : Mặt cắt bê tông đã bị nứt',
    'Covering material: : Vật liệu bao phủ',
    'Cover-meter, Rebar locator: : Máy đo lớp bê tông bảo hộ cốt thép',
    'Cover-plate: : Bản nối ốp, bản má',
    'Crack in development: : Vết nứt đang phát triển',
    'Crack width: : Độ mở rộng vết nứt',
    'Cracked concrete section: : Mặt cắt bê tông đã bị nứt',
    'Cracked state: : Trạng thái đã có vết nứt',
    'Cracking: : Nứt',
    'Cracking limit state: : Trạng thái giới hạn về mở rộng vết nứt',
    'Cracking moment: : Mô men gây nứt',
    'Cracking stress: : Ứng suất gây nứt',
    'Crane girder: : Giá cần trục; giàn cần trục',
    'Crane load: : sức nâng của cần trục, trọng tải của cần trục',
    'Creep: : Từ biến',
    'Crippling load: : Tải trọng phá hủy',
    'Critical load: : Tải trọng tới hạn',
    'Cross beam: : Dầm ngang, xà ngang',
    'Cross section: : Mặt cắt ngang',
    'Cross section at mid span: : Mặt cắt giữa nhịp',
    'Crushing load: : Tải trọng nghiền, tải trọng nén vỡ',
    'Crushing machine: : Máy nén mẫu thử bê tông',
    'Cube strength: : Cường độ khối vuông',
    'Cure to cure, curing: : Dưỡng hộ bê tông mới đổ xong',
    'Curing: : Bảo dưỡng bê tông trong lúc hóa cứng',
    'Curing temperature: : Nhiệt độ dưỡng hộ bê tông',
    'Curve: : Đường cong, đoạn tuyến cong',
    'Curved failure surface: : Mặt phá hoại cong',
    'Cutting machine: : Máy cắt cốt thép',
    'Cyclic load: : tải trọng tuần hoàn',
    'Cylinder, Test cylinder: : Mẫu thử bê tông hình trụ',
    'Changing load: : tải trọng thay đổi',
    'Characteristic strength: : Cường độ đặc trưng',
    'Checking concrete quality: : Kiểm tra chất lượng bê tông',
    'Chopped beam: : tia đứt đoạn',
    'Chord: : Thanh biên dàn',
    'CHS – Circular Hollow Section: : thép tiết diện tròn rỗng',
    'Dry concrete: : bê tông trộn khô, vữa bê tông cứng',
    'Dry guniting: : phun bê tông khô',
    'Duct: : ống chứa cốt thép dự ứng lực',
    'Dummy load: : tải trọng giả',
    'During stressing operation: : trong quá trình kéo căng cốt thép',
    'Dynamic load: : tải trọng động lực học',
    'Damage (local damage): : Hư hỏng (hư hỏng cục bộ)',
    'Data: : Dữ liệu (số liệu ban đầu)',
    'Dead load: : Tĩnh tải',
    'Dead load, Permanent load: : Tải trọng tĩnh (tải trọng thường xuyên)',
    'Dead to live load ratio: : Tỷ lệ giữa tĩnh tải và hoạt tải',
    'Dead weight load: : tĩnh tải',
    'Decision of establishing: : Quyết định thành lập',
    'Deck bridge: : Cầu có đường xe chạy trên',
    'Deck panel: : Khối bản mặt cầu đúc sẵn',
    'Deck plate girder: : Dầm bản thép có đường xe chạy trên',
    'Deck slab, deck plate: : Bản mặt cầu',
    'Deck-Truss interaction: : Tác động tương hỗ hệ mặt cầu với dàn',
    'Decompression limit state: : Trạng thái giới hạn mất nén',
    'Deep foundation: : Móng sâu',
    'Definitive evaluation: : Giá trị quyết toán',
    'Deflection: : Độ võng',
    'Deflection calculation: : Tính toán độ võng',
    'Deformation calculation: : Tính toán biến dạng',
    'Deformation due to Creep deformation: : Biến dạng từ biến',
    'Degradation: : Suy thoái (lão hóa)',
    'Delayed action: : Tác dụng làm chậm lại',
    'Demand load: : tải trọng yêu cầu',
    'Density of material: : Tỷ trọng của vật liệu',
    'Depth: : Chiều cao',
    'Depth of beam: : Chiều cao dầm',
    'Description: : Mô tả',
    'Design assumption: : Giả thiết tính toán',
    'Design load: : tải trọng tính toán, tải trọng thiết kế',
    'Dimensionless coefficient: : Hệ số không có thứ nguyên',
    'Dimensioning: : Xác định sơ bộ kích thước',
    'Dynamic: : Động lực học',
    'Dynamic force: : Lực động',
    'Direct-acting load: : Tải trọng tác động trực tiếp',
    'Discontinuous load: : Tải trọng không liên tục',
    'Discharge capacity: : Khả năng tiêu nước',
    'Displacement: : Chuyển vị',
    'Disposable load: : Tải trọng có ích',
    'Distance center to center of: : Khoảng cách từ tâm đến tâm của các',
    'Distance center to center of beams: : Khoảng cách từ tim đến tim của các dầm',
    'Distributed load: : Tải trọng phân bố',
    'Distributing reinforcement: : Cốt thép phân bố',
    'Distribution coefficient: : Hệ số phân bố',
    'Distribution width for wheel loads: : Chiều rộng phân bố của tải trọng bánh xe',
    'Divergent beam: : chùm phân kỳ',
    'DL – Dead Load: : Tĩnh tải',
    'DN – Diameter Nominal: : Đường kính danh định',
    'Double angle: : thép góc ghép thành hình T',
    'Double deck bridge: : Cầu hai tầng',
    'Double strut trussed beam: : Dầm tăng cứng hai trụ chống',
    'Drafting: : Vẽ kỹ thuật',
    'Drainage: : Hệ thống thoát nước, sự thoát nước',
    'Draw beam: : Dầm nâng, cần nâng',
    'Drawbar load: : Lực kéo ở móc',
    'Ductile material: : Vật liệu co dãn được (kim loại)',
    'Dummy load: : tải trọng giả',
    'Durability: : Độ bền lâu (tuổi thọ)',
    'During stressing operation: : Trong quá trình Kéo căng cốt thép',
    'DWV – Drainage, Waste and Vent: : Thoát nước, Nước thải & Thông hơi',
    'Dye penetrant examination: : Phương pháp kiểm tra bằng thấm chất màu',
    'Dynamic test: : Thử nghiệm động học',
    'Dynamic (al) load: : Tải trọng động lực học',
    'Early strength concrete: : bê tông hóa cứng nhanh',
    'Eccentric load: : tải trọng lệch tâm',
    'Effective depth at the section: : chiều cao có hiệu',
    'Gunned concrete: : bê tông phun',
    'Gusset plate: : bản nốt, bản tiết điểm',
    'Gust load: : tải trọng khi gió giật',
    'Gypsum concrete: : bê tông thạch cao',
    'Half- beam: : dầm nửa',
    'Half-latticed girder: : giàn nửa mắt cáo',
    'Hanging beam: : dầm treo',
    'H-beam: : dầm chữ “h”',
    'Radial load: : tải trọng hướng kính',
    'Radio beam (-frequency): : chùm tần số vô tuyến điện',
    'Railing load: : tải trọng lan can',
    'Railing: : lan can trên cầu',
    'Rammed concrete: : bê tông đầm',
    'Rated load: : tải trọng danh nghĩa',
    'Ratio of non- prestressing tension reinforcement: : tỷ lệ hàm lượng cốt thép thường trong mặt cắt',
    'Ratio of prestressing steel: : tỷ lệ hàm lượng cốt thép dự ứng lực',
    'Ready-mixed concrete: : bê tông trộn sẵn',
    'Rebound number: : số bật nảy trên súng thử bê tông',
    'Split beam: : dầm ghép, dầm tổ hợp',
    'Sprayed concrete: : bê tông phun',
    'Spring beam: : dầm đàn hồi',
    'Square hollow section: : thép hình vuông rỗng',
    'Stack of bricks: : đống gạch, chồng gạch',
    'Stacked shutter boards (lining boards): : đống vụn gỗ cốp pha, chống ván gỗ cốp pha',
    'Stamped concrete: : bê tông đầm',
    'Standard brick: : gạch tiêu chuẩn',
    'Web girder: : giàn lưới thép, dầm đặc',
    'Web reinforcement: : cốt thép trong sườn dầm',
    'Welded plate girder: : dầm bản thép hàn',
    'Welded wire fabric (welded wire mesh): : lưới cốt thép sợi hàn',
    'Wet concrete: : vữa bê tông dẻo',
    'Wheel load: : áp lực lên bánh xe',
    'Whole beam: : dầm gỗ',
];
